### ISSUE TITLE
ImportError: cannot import name 'Binary' from 'sqlalchemy'

### ISSUE THREAD

**Issue by gracefoong** [creativetimofficial/argon-dashboard-flask#3]
from sqlalchemy import Binary, Column, Integer, String
ImportError: cannot import name 'Binary' from 'sqlalchemy' (C:\Users\kenqq\AppData\Local\Programs\Python\Python38\lib\site-packages\sqlalchemy\__init__.py)

To use this template for my project used as a guideline but i met this error, how to solve it?

**Comment by app-generator** [comment]
Hello @gracefoong, 

Thank you for using our products. This problem has been fixed in the latest release. 
Please use a fresh install (if not already), create a virtual environment, and install dependencies using the command: 

`pip3 install -r requirements.txt`

Check the installed version of `flask_sqlalchemy` and `sqlalchemy` using python console:

```python
$ python
>>> import sqlalchemy
>>> sqlalchemy.__version__ 
>>> 
>>> import flask_sqlalchemy
>>> flask_sqlalchemy.__version__
```

Let us know the output.

**Comment by app-generator** [comment]
P.S. The sample output on Windows:

```bash
(env) PS > python.exe
```

```python
Python 3.8.4 (tags/v3.8.4:dfa645a, Jul 13 2020, 16:46:45) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sqlalchemy
>>> import flask_sqlalchemy
>>> sqlalchemy.__version__
'1.3.23'
>>> flask_sqlalchemy.__version__
'2.4.4'
>>>
```

**Comment by app-generator** [comment]
Hello @gracefoong, 

We assume the problem was fixed.  

Let us know if you need further assistance.
